### ISSUE TITLE
Blend micro range...!

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#100]
hai 

i am using a blend micro to make my project. i am programming my board from codebender.cc by using bleperipheral library.
Now i have done a range test on my board  so i can only connect in a range of 13M.
So my question is can i increase the range...? if so how can i do that.

thank you.

**Comment by sandeepmistry** [comment]
@iqbalpalemad 

> So my question is can i increase the range...?

Please look at the API documentation prior to asking these types of questions.

For the nRF8001 based boards, the maximum TX power is 0 dB. This is the default used by the library: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/API.md#set-tx-power
