### ISSUE TITLE
Best BLE device...?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#101]
Hai sandeep

i am currently working with a iot project which connects some sensor through ble. So i was started the project with blend micro.But the problem with blend micro is the range of communication.I have done a range test with blend micro.But the range was just 15M. So i need your help to choose a suitable ble device for my project.

actually i need at least 100 feet of communication range. And i want to do it with arduino so can you please suggest me a arduino compatible ble device with   high range.............?

thank you

**Comment by sandeepmistry** [comment]
Hi @iqbalpalemad,

I have not done much testing for range, so cannot answer this question. It really depends on the antenna design.

I would suggest you try out an nRF51822 or nRF52 based board, since you can set a higher TX power.
