### ISSUE TITLE
Reduce power consumption...................?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#106]
I am using a ble nano to transmit the state of three sensors in which one is digital and other two are analog.
Here i want to reduce the power consumption as much as low.

 for that i need to disable the  uart.  and i have already  adjusted Tx power and Tx interval.Now the current in the whole setup is approx to my desired range without connecting any central to ble nano. So if i disable uart the current will be in my desired range.
But when a central is connected then the current will increase 4times as my range. So my question is
how can i disable uart in bleperipheral library and  can i transmit my sensor data through device local name repeatedly without connecting any central to it.
Or can i transmit my sensor data to my destination (central) without connecting them each other............?

**Comment by sandeepmistry** [comment]
> for that i need to disable the uart. 

That question is not related to this library, I suggest to ask about RedBearLab about this: https://github.com/RedBearLab/nRF51822-Arduino

Please only open issues specifically related to this library here, it is not a place for general questions regarding the board etc.
