### ISSUE TITLE
How to read input power......................?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#108]
Hai

in my project i want to read the input voltage applied to ble nano  from my battery to display the battery percent.
Have any built in function to read applied voltage...?

THANK YOU

**Comment by sandeepmistry** [comment]
This issue tracker is only for items relating to this library.

I suggest you ask your question here: https://github.com/RedBearLab/nRF51822-Arduino
