### ISSUE TITLE
permanent data storage in ble nano..........?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#113]
Hai 

i need to store some data permanently on my ble nano. So when i posted about this in redbear lab forum the suggested to check at this url. 
[ https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/src/BLEBondStore.cpp2](url) .

i am a beginner in this area so can you please give me an example program showing permanent data storage and retrieval of data from flash memory of ble nano.

thank you

**Comment by sandeepmistry** [comment]
@iqbalpalemad please follow up wi the the RedBearLab team on this item, as this topic is not directly related to this library.
