### ISSUE TITLE
How to scan.............?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#117]
Hai

i am using a ble nano board to broadcast some sensor data. and i need another ble nano is to scan the first ble nano and read the broadcast-ed value and do some action based on it. so how can i configure my second ble nano to scan and read the broadcast-ed data using this library.

thank you

**Comment by sandeepmistry** [comment]
@iqbalpalemad this library only supports peripheral mode, so scanning is not supported.
