### ISSUE TITLE
How to use Bond Store..........?

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#118]
hai

actually i am beginner.i dont know actually how to use the Bond Store command to persist data. can you please explain.......?
if you  give me an example program using bond store it will be so helpful to me...!
i am using ble nano.
 
thank you

**Comment by sandeepmistry** [comment]
@iqbalpalemad see answer in https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/113#issuecomment-267839691.
