### ISSUE TITLE
Configuration mode.

### ISSUE THREAD

**Issue by denisacostaq** [sandeepmistry/arduino-BLEPeripheral#119]
Have this code support for [configuration mode](https://github.com/google/eddystone/tree/master/configuration-service)?

**Comment by denisacostaq** [comment]
I can not add the ¨question¨ labe for the issue.

**Comment by sandeepmistry** [comment]
@denisacostaq there is no suppose to Eddystone configuration mode in this library currently. However, it should be straightforward to add, pull requests welcome.
