### ISSUE TITLE
BLECharacteristic vs. BLERemoteCharacteristic

### ISSUE THREAD

**Issue by cbolgiano** [sandeepmistry/arduino-BLEPeripheral#121]
What is the difference between BLECharacteristic and BLERemotrCharacteristic?  I tried to write to them both from central but the writes always fail.  I am using a NRF8001 BLE board.

**Comment by sandeepmistry** [comment]
@cbolgiano you'll have to use `BLECharacteristic` for local GATT attributes on the nRF8001, and `BLERemoteCharacteristic` to access GATT attributes on the connected central. See the examples folder for more details.
