### ISSUE TITLE
Temperature + Humidity APP

### ISSUE THREAD

**Issue by KingJimmy27** [sandeepmistry/arduino-BLEPeripheral#124]
I am just starting to use your temp_sensor example which looks like the function I require. It looks like it is working when viewed with B-BLE app but I cannot find an Android app to display the temp and humidity results.
Can you suggest one please?

**Comment by sandeepmistry** [comment]
@KingJimmy27 I would recommend nRF Master control panel.

It might not display the converted values, so you'll probably have to convert them.
