### ISSUE TITLE
mention softdevice in readme

### ISSUE THREAD

**Issue by jacobrosenthal** [sandeepmistry/arduino-BLEPeripheral#128]
Another issue that held me up this weekend was this library requires softdevice already be present, but doesnt mention it anywhere. Maybe just copy paste https://github.com/sandeepmistry/arduino-nRF5#flashing-a-softdevice to here?

**Comment by sandeepmistry** [comment]
Ya, that sounds good to add the link here.

We can also update the BLE section in nRF5 about selecting a soft device as per https://github.com/sandeepmistry/arduino-nRF5/issues/102.
