### ISSUE TITLE
Change BLE BLEUuid for EddyStone example?

### ISSUE THREAD

**Issue by XaviLC** [sandeepmistry/arduino-BLEPeripheral#133]
Hello,

I would like to know how can I modify the EddyStone example so that I can include my own BLEUuid,  I see in the code of that example that is a configurable parameter but I don't know how I can access to it.

Thanks in advance,

Regards

**Comment by sandeepmistry** [comment]
@XaviLC change this line: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/examples/Eddystone/EddystoneUID/EddystoneUID.ino#L20
