### ISSUE TITLE
Can anyone guide me how to program NRF51822 using Arduino IDE?

### ISSUE THREAD

**Issue by deepkap** [sandeepmistry/arduino-BLEPeripheral#134]
I am beginner for NRF51822. 
I have this board : [https://www.tanotis.com/products/tanotis-nrf51822-bluetooth-module-networking-module-wireless-communication?gclid=Cj0KEQjwnsPGBRDo4c6RqK-Oqu8BEiQAwNviCRQ49by-kmeBS09n_kP5e8Ycsf8Dwl1P7d0CamqwNpMaApAM8P8HAQ&variant=20624084165](url)

How can i program this using Arduino IDE?

Thank You!

**Comment by jacobrosenthal** [comment]
Looks like thats just a bare module. Youll need to hook it up to a programmer/debugger chip of some kind.

The professional tool is the segger jlink, https://www.adafruit.com/product/1369
The 1bit squared guys are getting popular https://1bitsquared.com/products/black-magic-probe
Or something? running the open source cmsisdap daplink firmware https://github.com/mbedmicro/DAPLink

Or forget that module for now until you're more comfortable and just buy one of the already supported boards that already has a programmer/debugger on board.
