### ISSUE TITLE
beacon scanner

### ISSUE THREAD

**Issue by cheeta1** [sandeepmistry/arduino-BLEPeripheral#138]
hi @sandeepmistry  thanks for the awesome library. i was wondering that if you or any one in the community can provide an example to scan beacons in the area. if not then point me to functions which i can use to implement this functionality.

thanks

**Comment by sandeepmistry** [comment]
@cheeta1 this is a peripheral only library, so it does (and never will) support Central mode and scanning.

**Comment by vanbwodonk** [comment]
Hi @sandeepmistry, can i develop Central mode and scanning using this library? Maybe I need too add another some source files from Nordic SDK? Sorry for noobs questions,
