### ISSUE TITLE
Generic nrf51822 support ?

### ISSUE THREAD

**Issue by reapqin** [sandeepmistry/arduino-BLEPeripheral#143]
i wired ch340 serial chip to read serial data.i wired p0,09 to txd and p0,11 to rxd.
but no serial data i can read from the serial port.

what can i do thanks.

**Comment by sandeepmistry** [comment]
@reapqin really depends on what Arduino core you are using for that board. This library is focused only on the BLE Peripheral stack and has nothing to do with Serial.
