### ISSUE TITLE
Ibeacon example not transmitting Major, Minor, Txpower 

### ISSUE THREAD

**Issue by vanbwodonk** [sandeepmistry/arduino-BLEPeripheral#144]
I try ibeacon with nrf52 example, ibeacon scanned with missing major, minor and txpower.
Then i check data transmitting with nRF connect on android. RAW data showed only uuid. This RAW data i record from nRF connect.

`0x02010615FF4C000215A196C876DE8C4C47AB5AD7AFD5AE7127 `

Last 16 byte must from uuid. 
-Arduino -
`char* uuidString             = "a196c876-de8c-4c47-ab5a-d7afd5ae7127";`
-RAWdata-
`A196C876DE8C4C47AB5AD7AFD5AE7127`

Any suggestion?

**Comment by sandeepmistry** [comment]
@vanbwodonk could you please try the change from PR #148 and provide your feedback.

**Comment by vanbwodonk** [comment]
@sandeepmistry it's worked. Major, minor, TXpower now transmitted. Thanks !!

**Comment by sandeepmistry** [comment]
@vanbwodonk great, thanks for trying it out. I've merged #148.
