### ISSUE TITLE
No text recived over BLE

### ISSUE THREAD

**Issue by bossesand** [sandeepmistry/arduino-BLEPeripheral#147]
These funtions does not work, probably a library version issue in the compiler distribution, Google indicates this.
#include < cassert >
#include < iomanip>
#include < iostream >
#include < ostream >
I need them to convert signed floats to a string of 8 Bytes that can be sent with 
a NUS print command over BLE to save transmission time like this bleuart.print(quatString); 

I also want to have the format String as a concationated string  "2," + quatString + "," to be sent as one Gatt message with a bleuart.println(quatString)

This is the format of the array 
float quat[4] = {1.0f, 0.0f, 0.0f, 0.0f};    // vector to hold quaternion
    quat[0] = (float)(quatCount[0])/16384.;    
    quat[1] = (float)(quatCount[1])/16384.;  
    quat[2] = (float)(quatCount[2])/16384.;   
    quat[3] = (float)(quatCount[3])/16384.;

**Comment by sandeepmistry** [comment]
Closing this for now, as it doesn't seem related to this library. Please provide a full sketch if it is ...
