### ISSUE TITLE
TimerOne library for NRF51822 ?

### ISSUE THREAD

**Issue by mustafaevrenpolat** [sandeepmistry/arduino-BLEPeripheral#176]
Which library is required for NRF51822.

https://code.google.com/archive/p/arduino-timerone/downloads

TimerOne-r11.zip or TimerOne-v9.zip doesnt work

I'm getting an error for temp_sensor example :
\Arduino\libraries\TimerOne/TimerOne.h:39:20: fatal error: avr/io.h: No such file or directory

Regards

**Comment by sandeepmistry** [comment]
@mustafaevrenpolat there is no TimerOne library for the nRF51 as far as I know. The example that uses it in this library is targeted for AVR based boards.
