### ISSUE TITLE
Is it possible to implement BLECentral functions?

### ISSUE THREAD

**Issue by dmikhalsky** [sandeepmistry/arduino-BLEPeripheral#177]
Given the functions are implemented in arduino.org fork of the library, it shouln't be very difficult to merge?

**Comment by sandeepmistry** [comment]
@dmikhalsky it would be possible for nRF51 and nRF52 based boards, but not the nRF8001 chips.

There is a little discussion for the preferred road map in https://github.com/sandeepmistry/arduino-BLEPeripheral/pull/155#issuecomment-304553514.
