### ISSUE TITLE
Send data from nRF51822 DHT22 to Raspberry Pi 3 using python

### ISSUE THREAD

**Issue by Chop91** [sandeepmistry/arduino-BLEPeripheral#190]
As the topic says, I want to create a bunch of wireless temperature sensors, which should send their data to server on my raspberry pi3.

Yesterday I started playing around with the serial example and managed to send the data of the DHT22 to the nRF Toolbox and the nRF UART app. Today I tried to write a simple python program using pybluez to receive my temperature data, but nothing I tried seems to work.

Maybe someone tried something similar and can explain me what I have to do to get my temperature data from my nRF51822 to my raspberry pi3.

**Comment by sandeepmistry** [comment]
You might find reading a copy of http://makebluetooth.com useful.
