### ISSUE TITLE
Measuring Temperature using Inbuilt Sensor and battery voltage  in Nrf52832

### ISSUE THREAD

**Issue by RajeshkumarC** [sandeepmistry/arduino-BLEPeripheral#203]
Hi ,
I am new to github and i don't know whether to post these questions in issue part. If wrong means sorry.
I read your BLEPeripheral library. I want to clarify is there any
1)  Function in your library will help to measure temperature using inbuilt temperature sensor of nrf52832.

2) Inbuilt function to measure the battery voltage using the VDD given to the chip. 

since the above two are inbuilt in the Nrf52832, it will be more useful rather than using external components which may lead to current consumption. In such a case the  battery life of the IC wont last for years.

**Comment by sandeepmistry** [comment]
Both are not possible without changes to library. There is some discussion in https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/33 that you might find useful.
