### ISSUE TITLE
Modify iBeacon advertising packet while transmitting

### ISSUE THREAD

**Issue by rwadhwa25** [sandeepmistry/arduino-BLEPeripheral#212]
Hi,
Is there any way to change the advertising data (eg: Minor) based on some conditions, say a sensor reading? If it's possible could you please provide me with some direction on how to proceed or which library to modify if that's needed.
Thanks!

**Comment by sandeepmistry** [comment]
You'll have to try to call `blePeripheral.end()` and the original setup stuff again to change parameters.
