### ISSUE TITLE
save pairing data of more than one device

### ISSUE THREAD

**Issue by cheeta1** [sandeepmistry/arduino-BLEPeripheral#213]
hi there. i am trying to make a hid keyboard which can save the pairing data of multiple mobile. i was going through the code and found the following lines in nrf51822.cpp

![image](https://user-images.githubusercontent.com/25286049/35957483-9ed7f422-0cbd-11e8-8852-ee43e7a85a92.png)

does that means that in this library there is only support of saving bonding data of one device?

i looked at the nordic sdk and they have a list for the bonded devices

![image](https://user-images.githubusercontent.com/25286049/35957558-f02a1382-0cbd-11e8-8f85-c0926f8c4f83.png)

can we make a similar thing in this library as well? 

this kind of functionality i intend to implement
https://www.youtube.com/watch?v=zZRuJXXi-Ew&feature=youtu.be

thanks again for the awesome library

**Comment by sandeepmistry** [comment]
> does that means that in this library there is only support of saving bonding data of one device?

That's correct.



> can we make a similar thing in this library as well?

Sure, the code is open source so modify as you wish.

The nRF8001 only supports a single paired device, so the nRF51 code is based around this.
