### ISSUE TITLE
Port over the examples from arduino.cc/en/Tutorial/

### ISSUE THREAD

**Issue by probonopd** [sandeepmistry/arduino-BLEPeripheral#216]
We should port over the example sketches for the Genuino 101 CurieBLE:

- https://www.arduino.cc/en/Tutorial/Genuino101CurieBLEHeartRateMonitor
- https://www.arduino.cc/en/Tutorial/Genuino101CurieBLEBatteryMonitor
- https://www.arduino.cc/en/Tutorial/Genuino101CurieBLEButtonLED
- https://www.arduino.cc/en/Tutorial/Genuino101CurieBLECallbackLED
- https://www.arduino.cc/en/Tutorial/Genuino101CurieBLELED

These have nice documentation and work with the Nordic smartphone app.

**Comment by sandeepmistry** [comment]
I think there are already too many examples in this library.

LED, LED callback, and LED switch (button) examples are already present.
