### ISSUE TITLE
How to use this Library to use the transreceiver on the NRF chip without the BLE stack?

### ISSUE THREAD

**Issue by suveergarg** [sandeepmistry/arduino-BLEPeripheral#227]
Hi , 

I wish to build a sensor mesh using BLE nano, where each node can be a master or slave. I am hoping to use the trans receiver on the chip without the BLE stack to perform this... since this library only supports peripheral roles. Please let me know if there is a hack for this.

Thanks

**Comment by sandeepmistry** [comment]
@suveergarg there are no hacks for it using this library.
