### ISSUE TITLE
how to operate in Central mode? that is, in Client mode

### ISSUE THREAD

**Issue by antonioriccelli** [sandeepmistry/arduino-BLEPeripheral#228]
https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/161a4163f565be3cd5b62bbc59f0c2b522d82b02/src/BLECentral.cpp#L8

**Comment by sandeepmistry** [comment]
@antonioriccelli this is a peripheral mode only library.

**Comment by tpitman** [comment]
This is a great and simple peripheral library. Thank you.

Do you know of any libraries that will work with your Generic nRF Arduino library? I need Central functionality for my project.
