### ISSUE TITLE
Arduino Freeze

### ISSUE THREAD

**Issue by mitko9000** [sandeepmistry/arduino-BLEPeripheral#23]

**Comment by zrecommerce** [comment]
Do you have any serial monitor output?

Alex Albino
Sr. Fullstack Developer
Zend Certified Engineer
https://github.com/zrecommerce
https://github.com/femtoduino
https://github.com/femtoio

(707) 246-6864

**Comment by mitko9000** [comment]
Well what I did is to change nrf8001.cpp file inside case ACI_EVT_PIPE_STATUS
and commented everything now read and write is working.

**Comment by mitko9000** [comment]
Also bonding for HID mouse is not working at all cant bond with device

**Comment by sandeepmistry** [comment]
@mitko9000 I've addressed this with 051765c ... it didn't like dereferencing an unaligned uint64_t pointer, so I switched to using ```memcpy```.
