### ISSUE TITLE
Issue with nRF52-DK

### ISSUE THREAD

**Issue by jkpachunk** [sandeepmistry/arduino-BLEPeripheral#254]
I have used this library in the past for the nRF52-DK in the Platformio IDE. Recently though whenever I go to compile the sketch I receive the following error:

"ble_gatts.h: No such file or directory"

I have tried compiling the remote_test.ino sketch in both the Arduino and Platformio IDE and I keep getting the same error. What could potentially be causing this issue?

**Comment by SL06** [comment]
From what I have read, you have o flash the Softdevice first and it will solve the problem, 
Good luck.

**Comment by jkpachunk** [comment]
Thank you very much that was the issue! I found out how to include a soft device through the Platformio tutorials.
