### ISSUE TITLE
Freeze on blePeripheral.begin();

### ISSUE THREAD

**Issue by jLynx** [sandeepmistry/arduino-BLEPeripheral#291]
Hi 

I have just designed a NRF51822 board and all my test code seems to be working apart from getting bluetooth to work.

My code always seems to freeze on the line `blePeripheral.begin();`

Looking at the LED sketch, it freezes on line 38 https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/161a4163f565be3cd5b62bbc59f0c2b522d82b02/examples/led/led.ino#L38

Here is my config:
![image](https://user-images.githubusercontent.com/4393979/117768294-4e108780-b286-11eb-801b-b3611cd873c9.png)

(Note: Right now there is no antenna on the board as I am waiting for it to show up, but I doubt that will have anything to do with the code not executing) 

If you need any more information please let me know.

Here is the function it freezes on https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/161a4163f565be3cd5b62bbc59f0c2b522d82b02/src/BLEPeripheral.cpp#L71

**Comment by jLynx** [comment]
Seems like there are a few other people with the same issue, but lacking detail.

- https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/269
- https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/268
- https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/257
- https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/22 (Answered but no fix found)
- https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/146
- https://github.com/sandeepmistry/arduino-nRF5/issues/370

**Comment by jLynx** [comment]
Seems like it could be an issue with the BLE_REQ, BLE_RDY, BLE_RST pins. Will update if I find any more information

**Comment by jLynx** [comment]
Here is my basic schematic 
![image](https://user-images.githubusercontent.com/4393979/117897579-3a613180-b317-11eb-9b1f-c8ed885c3d37.png)

**Comment by jLynx** [comment]
If I understand correctly, they should all be -1? I have tried this but still no success

**Comment by jLynx** [comment]
Fixed my issue!
The fix was to select RC Oscillator instead of Crystal Oscillator
![image](https://user-images.githubusercontent.com/4393979/117900956-72b83e00-b31e-11eb-96da-b4e8cbc5aa11.png)

https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/161a4163f565be3cd5b62bbc59f0c2b522d82b02/src/nRF51822.cpp#L106

**Comment by jLynx** [comment]
As much as this has fixed the initial issue to get me going, I have found that the RC Oscillator is using the internal RC oscillator and not the External 32.768 kHz crystal (Crystal Oscillator). Will be doing more research into why its not able to start with this selected. I am assuming it something to do with this line
![image](https://user-images.githubusercontent.com/4393979/118553200-1e94da00-b7b4-11eb-9a38-915b29995146.png)
maybe with the accuracy being off with my crystal

**Comment by LiveRock** [comment]
can we reconfig BLE_REQ, BLE_RDY, BLE_RST pins?
