### ISSUE TITLE
New approach: Write bondstore before sending the BLEDeviceBonded() event in the BLE_GAP_EVT_AUTH_STATUS case.

### ISSUE THREAD

**Issue by bojh** [sandeepmistry/arduino-BLEPeripheral#32]
To have a more consistent status it would make sense to write the bondstore to the EPROM memory before notifying the application. May be, the peripheral will be switched off before a disconnect from the central will arrive, the bond information will be lost.

**Comment by sandeepmistry** [comment]
@bojh I've made the change in https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/f1cd7bcb9df371b5369b99ca40f459f11f49cd7d.

The previous code was modelled after the nRF8001, which needed to be disconnected before retrieving the bond data.
