### ISSUE TITLE
iBeacon code is a little brittle around manufacturerData value

### ISSUE THREAD

**Issue by george-hawkins** [sandeepmistry/arduino-BLEPeripheral#37]
I'm raising an issue against code that I submitted!

The array holding the iBeacon `manufacturerData` is created on the stack - see [`iBeacon.cpp:14`](https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/ef8ede4a49984d4a74dc452945fad4f428fa1878/iBeacon.cpp#L14):
```c++
void iBeacon::begin(const char* uuidString, unsigned short major, unsigned short minor, char measuredPower) {
  unsigned char manufacturerData[MAX_UUID_LENGTH + 9]; // 4 bytes of header and 5 bytes of trailer.
```

I hadn't realized when calling `BLEPeripheral::setManufacturerData(...)` that it doesn't copy its input.

This doesn't matter as the only method that currently needs this data is also called from the `iBeacon::begin(...)` method so our data is luckily still in scope. But the minute we leave the `iBeacon::begin(...)` method the value of `BLEPeripheral::_manufacturerData` is junk.

I noticed this when I tried adding a getter alongside the existing `BLEPeripheral::setManufacturerData(...)`.

Sorry to post this issue without posting a fix - I could get around this problem another way in my code but I just wanted to point out the brittleness.

**Comment by sandeepmistry** [comment]
@george-hawkins thanks for bringing this up!

I've pushed https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/31db9ad815525ceb9ea773841835625f3fecd6ac which makes the manufacturer data a member variable of the ```iBeacon``` class.
