### ISSUE TITLE
Write a RemoteCharacteristic

### ISSUE THREAD

**Issue by andresrubiop** [sandeepmistry/arduino-BLEPeripheral#72]
Hello I am using the ANCS example and I am trying to write  the BLERemoteCharacteristic ancsControlPointCharacteristic for receive extra info in the ancsDataSourceCharacteristic.

Using this message.
struct AncsGetNotification
{
  unsigned char commandId;
  unsigned long notificationUid;
  unsigned char attributeId1;
  
};

What i am doing is to write just as the characteristic were a loca characteristic. So. Maybe can you guide me how to write remote characteristics,maybe is just the way i am doing and that is why is not working.

Thanks.

**Comment by sandeepmistry** [comment]
Hi @andresrubiop,

https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/examples/remote_test/remote_test.ino#L90-L96 might be useful.

You should also be careful about the endianness of the `unsigned long notificationUid;` member of the structure. The Apple ANCS docs will tell you if it's big or little endian.

**Comment by sandeepmistry** [comment]
I think this has been answered. I'm going to close it due to lack of activity.
