### ISSUE TITLE
iBeacon for nRF8001

### ISSUE THREAD

**Issue by danielcbit** [sandeepmistry/arduino-BLEPeripheral#78]
Hi.

I'd like to know why the iBeacon implementation only works with nRF51 devices currently.

Is it a hardware limitation?

Thanks.

**Comment by zrecore** [comment]
It's more likely a simpler explanation - no one has contributed the code
for other platforms yet.

**Comment by danielcbit** [comment]
Actually, to answer my on question, the iBeacon format needs more than 20 bytes, which is the max nRF8001 supports.
As it is an old radio, it has it's limitations.

**Comment by sandeepmistry** [comment]
@danielcbit yep, it's a h/w limitation. More details on the maximum for supported devices can be found here: https://github.com/sandeepmistry/arduino-BLEPeripheral/blob/master/API.md#manufacturer-data
