### ISSUE TITLE
Merging nR5 branch

### ISSUE THREAD

**Issue by sandeepmistry** [sandeepmistry/arduino-BLEPeripheral#81]
Hi @nihaopaul,

Do you have any feedback about merging the `nRF5` branch into master?

In the testing I've done things have looked good so far. What's your experience been?

Thanks.

**Comment by nihaopaul** [comment]
yeah, works a wonder for me! been using my branch with the changes for the last week with the nrf52 both devkit and custom board. thanks!

**Comment by sandeepmistry** [comment]
Closing this, there's a PR #83 is open now :)
