### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by SimonTheEngineer** [sandeepmistry/arduino-BLEPeripheral#87]
Hi, 

I'm trying to compile the starter.ino sketch for Arduino Uno R2 with Arduino IDE 1.6.12 but receiving the following error:

```
C:\Users\simon\AppData\Local\Temp\ccFggZdZ.ltrans5.ltrans.o: In function `BLEUtil::addressToString(unsigned char const*, char*) [clone .constprop.44]':

ccFggZdZ.ltrans5.o:(.text+0x1d4): relocation truncated to fit: R_AVR_7_PCREL against `no symbol'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.
```

Any help would be great!

**Comment by sandeepmistry** [comment]
Hi @SimonTheEngineer,

Thanks for letting me know, I've resolved the compile issue with IDE 1.6.12 in https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/8f3aa2484cd97e48e14beb225413420b78e0ce42.

Could you try it out locally and report the results? Newer Arduino IDE's introduced LTO (link time optimization) for AVR boards like the Uno, so it didn't like that code.
