### ISSUE TITLE
What are the correct pins for mod-nrf8001

### ISSUE THREAD

**Issue by baloodevil** [sandeepmistry/arduino-BLEPeripheral#94]
I'm trying to determine which pins to use according to [the table](https://github.com/sandeepmistry/arduino-BLEPeripheral#pinouts).  If I used Adafruit, I would know, but I don't see the chip that I have in the table, and the [nordic pinout](https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/resources/MOD-NRF8001-pinout.png) diagram doesn't have REQ, RDY, RST.  There are labels that are close... REQN(7), RDNY(10), RST(3), but I am not sure if that is what is intended.  I'm new to SPI, UART, etc., so wanted to double-check before frying a BLE chip. 

Trying to follow [this tutorial](https://www.youtube.com/watch?v=9NnIxLxbbnM#t=227.140255), which references UART, even though the pins mentioned on this page (SCK, MOSI, REQN) seem to indicate that it is SRI.  I've lowered the voltage coming from the Arduino to each of those pins to be 3.3, according to [this page](https://www.olimex.com/Products/Modules/RF/MOD-nRF8001/).

**Comment by sandeepmistry** [comment]
Hi @baloodevil,

You can use the same pins as ones listed for Adafruit in the table on the Arduino side. You must use SPI, the UART pins are for test mode only. The close labels you mentioned are fine, the one's listed in the read me don't have the 'N', please try them out.

Let me know how things go, I'm going to close this for now, but we can continue the discussion here. We can update the read me accordingly when you have things working.
