### ISSUE TITLE
read handler

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#95]
hai 
you have done an excellent work.thanks for that
and i would like to know how to handle a read request.
actually this is my need 

i have to activate my sensor only when a user request a read characteristic
how can i do that...?

**Comment by sandeepmistry** [comment]
Hi @iqbalpalemad,

Thanks for the positive feedback!

What board are you using? This might be possible with nRF51 based boards only.

I'm closing this as a duplicate request, #71 is already open to track this, please follow it for updates.
