### ISSUE TITLE
how to make pairing between device and board

### ISSUE THREAD

**Issue by iqbalpalemad** [sandeepmistry/arduino-BLEPeripheral#96]
i am using blend micro in my project.i want to connect only one device to the blend micro and i have to block all other request to the board when there is a paired device.and i want to connect one another device only when a certain conditions are occurred how can i do that...........?

**Comment by sandeepmistry** [comment]
Hi @iqbalpalemad,

A white list is not supported at this time, and probably won't be in the road map. As a workaround you can add an event listener for the connect event and disconnect if the central's address doesn't meet you expectations.

**Comment by sandeepmistry** [comment]
Question answered, closing.
